gems:
  - jekyll-redirect-from
title: Shintaro Sakai
url: "https://shinshinsakasaka.github.io"
#baseurl: "/me"
markdown: kramdown
favicon: sherlock.jpg

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Github"
   link: "https://github.com/shinshinsakasaka"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
